repos:
  - repo: local
    hooks:
      - id: make-format
        name: Run format
        entry: make format
        language: system
        files: ^pylabrobot/.*$
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
        args: ["--force-exclude"]