[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
dot_acn = ".acn"
dot_fot = ".fot"
dot_ist = ".ist"
OT = "OT"
ot = "ot"
ser = "ser"
ba = "ba"
nd = "nd"
PN = "PN"
tro = "tro"
FO = "FO"
UE = "UE"
commutated = "commutated"
commutating = "commutating"
DOUT = "DOUT"
inconsistence = "inconsistence"
mis = "mis"
RHE = "RHE"
"ASEND" = "ASEND"

[files]
extend-exclude = [
    "*.ipynb"
]
