name: Build and Publish Documentation

on:
  push:
    branches: main

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update packages
        run: sudo apt-get update

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -e '.[dev]'

      - name: Remove old documentation
        run: |
          rm -rf docs/build
          rm -rf docs/_autosummary

      - name: Build new documentation
        run: make docs

      - name: Commit generated documentation
        run: |
          cd docs/build
          git init
          touch .nojekyll
          echo 'docs.pylabrobot.org' > CNAME
          git add -A
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m 'deploy docs'

      - name: Push to docs branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          directory: ./docs/build/
